# Generated by Django 5.2.17 on 2026-10-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_staff', False), ('is_superuser', True), _negated=True), name='users_is_superuser_requires_staff', violation_error_message='A superuser must also be staff.'),
        ),
    ]
