# Generated by Django 5.2.17 on 2026-10-03 08:25

import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_users_is_superuser_requires_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_digest', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('failed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'login_failures',
            },
        ),
        migrations.AlterConstraint(
            model_name='user',
            name='users_email_normalized',
            constraint=models.CheckConstraint(condition=models.Q(('email', django.db.models.functions.text.Lower('email')), models.Q(('email__regex', '\\s'), _negated=True)), name='users_email_normalized', violation_error_message='Email must be lowercase, without spaces.'),
        ),
        migrations.AddIndex(
            model_name='loginfailure',
            index=models.Index(fields=['email_digest', 'failed_at'], name='login_failures_digest_idx'),
        ),
        migrations.AddIndex(
            model_name='loginfailure',
            index=models.Index(fields=['ip', 'failed_at'], name='login_failures_ip_idx'),
        ),
    ]
