# Generated by Django 5.2.17 on 2026-10-04 13:43

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_login_failures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.validators.validate_email_is_ascii]),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__regex', '^[\\x00-\\x7f]*$')), name='users_email_ascii', violation_error_message='Email must use only ASCII characters.'),
        ),
    ]
